name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['17', '21']
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up Gradle
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew clean build --continue --scan -PtestToolchain=${{ matrix.java-version }}
